Get http://localhost:3001/api/persons

###
DELETE http://localhost:3001/api/persons/2

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Moine Botista",
  "number": "123-123456"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "123-123456"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Gollum"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

###
POST https://phonebook-backend-6usi.onrender.com/api/persons
Content-Type: application/json

{
  "name": "Gail in Storm",
  "number": "000-000000"
}

###
DELETE https://phonebook-backend-6usi.onrender.com/api/persons/3
