POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Mr Peabody won",
  "url": "someURL",
  "likes": 12
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Storm defeated Deeboo",
  "url": "anotherURL",
  "likes": 12
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "chewara",
  "name": "Na",
  "password": "salainen"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "Botista",
  "name": "Mr Peabody",
  "password": "salainen"
}